version: '3.9'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000" 
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mydb  
    depends_on:
      - mongo
    volumes:
      - .:/app  

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"  
    volumes:
      - mongo_data:/data/db  

volumes:
  mongo_data:
