apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-project-configmap
  namespace: devops
data:
  MONGO_URL: mongodb.devops.svc.cluster.local 
  MONGO_DATABASE: mydb  
  MONGO_USER: myuser

---
apiVersion: v1
kind: Secret
metadata:
  name: devops-project-secret
  namespace: devops
type: Opaque
data:
  mongo-password: bXlwYXNzd29yZA== 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-deployment
  namespace: devops
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: flask-project
  template:
    metadata:
      labels:
        app: flask-project
    spec:
      containers:
        - name: flask-project
          image: sekuloska/devops_project-web
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: devops-project-configmap
          env:
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devops-project-secret
                  key: mongo-password